name: deploy_master

on:
    push:
        branches:
            - 'master'

jobs:
    deploy_production:
        uses: ./.github/workflows/linode-deployment.yml
        with:
            envname: master
            deploy_path: '~/webui-production/management-ui'
            port: '8000'
        secrets:
            host: ${{ secrets.LINODE_IP }}
            user: ${{ secrets.USER }}
            private_key: ${{ secrets.PRIVATE_KEY }}
